// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTemplateRenderer is an autogenerated mock type for the TemplateRenderer type
type MockTemplateRenderer struct {
	mock.Mock
}

type MockTemplateRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRenderer) EXPECT() *MockTemplateRenderer_Expecter {
	return &MockTemplateRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function with given fields: templateID, data
func (_m *MockTemplateRenderer) Render(templateID string, data map[string]interface{}) (string, string, error) {
	ret := _m.Called(templateID, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) (string, string, error)); ok {
		return rf(templateID, data)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) string); ok {
		r0 = rf(templateID, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]interface{}) string); ok {
		r1 = rf(templateID, data)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, map[string]interface{}) error); ok {
		r2 = rf(templateID, data)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTemplateRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockTemplateRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - templateID string
//   - data map[string]interface{}
func (_e *MockTemplateRenderer_Expecter) Render(templateID interface{}, data interface{}) *MockTemplateRenderer_Render_Call {
	return &MockTemplateRenderer_Render_Call{Call: _e.mock.On("Render", templateID, data)}
}

func (_c *MockTemplateRenderer_Render_Call) Run(run func(templateID string, data map[string]interface{})) *MockTemplateRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *MockTemplateRenderer_Render_Call) Return(subject string, body string, err error) *MockTemplateRenderer_Render_Call {
	_c.Call.Return(subject, body, err)
	return _c
}

func (_c *MockTemplateRenderer_Render_Call) RunAndReturn(run func(string, map[string]interface{}) (string, string, error)) *MockTemplateRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateRenderer creates a new instance of MockTemplateRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRenderer {
	mock := &MockTemplateRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
