// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	notification "notification-service/internal/notification"

	mock "github.com/stretchr/testify/mock"
)

// MockChannel is an autogenerated mock type for the Channel type
type MockChannel struct {
	mock.Mock
}

type MockChannel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChannel) EXPECT() *MockChannel_Expecter {
	return &MockChannel_Expecter{mock: &_m.Mock}
}

// CanHandle provides a mock function with given fields: notificationType
func (_m *MockChannel) CanHandle(notificationType notification.NotificationType) bool {
	ret := _m.Called(notificationType)

	if len(ret) == 0 {
		panic("no return value specified for CanHandle")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(notification.NotificationType) bool); ok {
		r0 = rf(notificationType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockChannel_CanHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanHandle'
type MockChannel_CanHandle_Call struct {
	*mock.Call
}

// CanHandle is a helper method to define mock.On call
//   - notificationType notification.NotificationType
func (_e *MockChannel_Expecter) CanHandle(notificationType interface{}) *MockChannel_CanHandle_Call {
	return &MockChannel_CanHandle_Call{Call: _e.mock.On("CanHandle", notificationType)}
}

func (_c *MockChannel_CanHandle_Call) Run(run func(notificationType notification.NotificationType)) *MockChannel_CanHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.NotificationType))
	})
	return _c
}

func (_c *MockChannel_CanHandle_Call) Return(_a0 bool) *MockChannel_CanHandle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannel_CanHandle_Call) RunAndReturn(run func(notification.NotificationType) bool) *MockChannel_CanHandle_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannelType provides a mock function with no fields
func (_m *MockChannel) GetChannelType() notification.ChannelType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChannelType")
	}

	var r0 notification.ChannelType
	if rf, ok := ret.Get(0).(func() notification.ChannelType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(notification.ChannelType)
	}

	return r0
}

// MockChannel_GetChannelType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelType'
type MockChannel_GetChannelType_Call struct {
	*mock.Call
}

// GetChannelType is a helper method to define mock.On call
func (_e *MockChannel_Expecter) GetChannelType() *MockChannel_GetChannelType_Call {
	return &MockChannel_GetChannelType_Call{Call: _e.mock.On("GetChannelType")}
}

func (_c *MockChannel_GetChannelType_Call) Run(run func()) *MockChannel_GetChannelType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannel_GetChannelType_Call) Return(_a0 notification.ChannelType) *MockChannel_GetChannelType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannel_GetChannelType_Call) RunAndReturn(run func() notification.ChannelType) *MockChannel_GetChannelType_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, payload
func (_m *MockChannel) Send(ctx context.Context, payload *notification.NotificationPayload) (*notification.NotificationResponse, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *notification.NotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notification.NotificationPayload) (*notification.NotificationResponse, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notification.NotificationPayload) *notification.NotificationResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notification.NotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notification.NotificationPayload) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChannel_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockChannel_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *notification.NotificationPayload
func (_e *MockChannel_Expecter) Send(ctx interface{}, payload interface{}) *MockChannel_Send_Call {
	return &MockChannel_Send_Call{Call: _e.mock.On("Send", ctx, payload)}
}

func (_c *MockChannel_Send_Call) Run(run func(ctx context.Context, payload *notification.NotificationPayload)) *MockChannel_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*notification.NotificationPayload))
	})
	return _c
}

func (_c *MockChannel_Send_Call) Return(_a0 *notification.NotificationResponse, _a1 error) *MockChannel_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChannel_Send_Call) RunAndReturn(run func(context.Context, *notification.NotificationPayload) (*notification.NotificationResponse, error)) *MockChannel_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChannel creates a new instance of MockChannel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChannel {
	mock := &MockChannel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
